image:
  repository: harbor.i2cv.io/cosmichorizon/s3-watcher # e.g. ghcr.io/yourorg/s3-watcher
  tag: "latest"
  pullPolicy: Always

# AWS credentials — populated via Kubernetes Secret (see secret.yaml)
# Set these in your ArgoCD application or via `helm install --set`
aws:
  region: eu-west-1
  existingSecret: "s3-watcher-creds" # set to use a pre-existing secret, e.g. "s3-watcher-creds"
  accessKeyId: "" # ignored if existingSecret is set
  secretAccessKey: "" # ignored if existingSecret is set

s3:
  bucketName: "atreides-gold-customer-data-prod-a1ce8606" # required
  prefix: "clairvoyant/sample/" # optional folder prefix
  pollIntervalSeconds: 86400

credentials:
  existingSecret: "signal-monitor-credentials"
  gdrive:
    existingSecret: "google-oauth" # Secret containing token.json and credentials.json

resources:
  requests:
    cpu: 2000m
    memory: 2Gi
  limits:
    cpu: 4000m
    memory: 4Gi

# Number of replicas — keep at 1 to avoid duplicate log output
replicaCount: 1

watcher:
  enabled: false

ingestionJob:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
  name: ""

imagePullSecrets:
  - name: s-hxl2n
nameOverride: ""
fullnameOverride: ""

extraVolumes:
  - name: certs-volume
    secret:
      secretName: cosmic-npe
  - name: dod-ca-volume
    secret:
      secretName: dod-ca-pem

# Mount paths for extra volumes
extraVolumeMounts:
  - name: certs-volume
    mountPath: "/certs"
    readOnly: true
  - name: dod-ca-volume
    mountPath: "/ca-certs"
    readOnly: true

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/s3-watcher)$ $1/ permanent;
  hosts:
    - host: test-cosmichorizon-worker-68a3110f01feebd0.elb.us-gov-west-1.amazonaws.com
      paths:
        - path: /()(s3-watcher(?:/|$).*)
          pathType: ImplementationSpecific
          backendName: analyze
          backendPort: 8000
  tls: []

clickhouse:
  enabled: true
  storage: 10Gi
  storageClass: "cosmichorizon-ebs-gp3"
