{{- if .Values.ingress.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3-watcher.fullname" . }}-analyze
  labels:
    app: {{ include "s3-watcher.name" . }}-analyze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "s3-watcher.name" . }}-analyze
  template:
    metadata:
      labels:
        app: {{ include "s3-watcher.name" . }}-analyze
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "s3-watcher.serviceAccountName" . }}
      containers:
        - name: analyze
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "analyze.py"]
          env:
            - name: CLICKHOUSE_HOST
              value: {{ include "s3-watcher.fullname" . }}-clickhouse
            - name: CLICKHOUSE_USER
              value: {{ .Values.clickhouse.user | quote }}
            - name: CLICKHOUSE_PASSWORD
              value: {{ .Values.clickhouse.password | quote }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.analyze.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-watcher.fullname" . }}-analyze
  labels:
    app: {{ include "s3-watcher.name" . }}-analyze
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ include "s3-watcher.name" . }}-analyze
{{- end }}
