{{- if not .Values.aws.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-watcher.fullname" . }}-creds
  labels:
    {{- include "s3-watcher.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws-access-key-id: {{ .Values.aws.accessKeyId | quote }}
  aws-secret-access-key: {{ .Values.aws.secretAccessKey | quote }}
{{- end }}
